import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Room from '#models/room'
import { Status } from '#types/status'

export default class extends BaseSeeder {
    public async run() {
        const existingRoom = await Room.query().first()

        if (!existingRoom) {
            await Room.createMany([
                {
                    type: 'M',
                    capacity: 4,
                    occupancyStatus: Status.DISPONIBLE,
                    availableSpots: 4,
                    location: 'Home A - Niveau-1 Chambre 1',
                    isAvailable: true,
                    description: 'Chambre 1 du Bloc A',
                },
                {
                    type: 'M',
                    capacity: 4,
                    occupancyStatus: Status.DISPONIBLE,
                    availableSpots: 4,
                    location: 'Home A - Niveau-1 Chambre 2',
                    isAvailable: true,
                    description: 'Chambre 2 du Bloc A',
                },
                {
                    type: 'M',
                    capacity: 4,
                    occupancyStatus: Status.DISPONIBLE,
                    availableSpots: 4,
                    location: 'Home A - Chambre 3',
                    isAvailable: true,
                    description: 'Chambre 3 du Bloc A',
                },
                {
                    type: 'M',
                    capacity: 4,
                    occupancyStatus: Status.DISPONIBLE,
                    availableSpots: 4,
                    location: 'Home A - Chambre 4',
                    isAvailable: true,
                    description: 'Chambre 4 du Bloc A',
                },
                {
                    type: 'M',
                    capacity: 4,
                    occupancyStatus: Status.DISPONIBLE,
                    availableSpots: 4,
                    location: 'Home A - Chambre 5',
                    isAvailable: true,
                    description: 'Chambre 5 du Bloc A',
                },

                {
                    type: 'M',
                    capacity: 4,
                    occupancyStatus: Status.DISPONIBLE,
                    availableSpots: 4,
                    location: 'Home B - Chambre 1',
                    isAvailable: true,
                    description: 'Chambre 1 du Bloc B',
                },
                {
                    type: 'M',
                    capacity: 4,
                    occupancyStatus: Status.DISPONIBLE,
                    availableSpots: 4,
                    location: 'Home B - Chambre 2',
                    isAvailable: true,
                    description: 'Chambre 2 du Bloc B',
                },
                {
                    type: 'M',
                    capacity: 4,
                    occupancyStatus: Status.DISPONIBLE,
                    availableSpots: 4,
                    location: 'Home B - Chambre 3',
                    isAvailable: true,
                    description: 'Chambre 3 du Bloc B',
                },
                {
                    type: 'M',
                    capacity: 4,
                    occupancyStatus: Status.DISPONIBLE,
                    availableSpots: 4,
                    location: 'Home B - Chambre 4',
                    isAvailable: true,
                    description: 'Chambre 4 du Bloc B',
                },
                {
                    type: 'M',
                    capacity: 4,
                    occupancyStatus: Status.DISPONIBLE,
                    availableSpots: 4,
                    location: 'Home B - Chambre 5',
                    isAvailable: true,
                    description: 'Chambre 5 du Bloc B',
                },

                {
                    type: 'M',
                    capacity: 4,
                    occupancyStatus: Status.DISPONIBLE,
                    availableSpots: 4,
                    location: 'Home C - Chambre 1',
                    isAvailable: true,
                    description: 'Chambre 1 du Bloc C',
                },
                {
                    type: 'M',
                    capacity: 4,
                    occupancyStatus: Status.DISPONIBLE,
                    availableSpots: 4,
                    location: 'Home C - Chambre 2',
                    isAvailable: true,
                    description: 'Chambre 2 du Bloc C',
                },
                {
                    type: 'M',
                    capacity: 4,
                    occupancyStatus: Status.DISPONIBLE,
                    availableSpots: 4,
                    location: 'Home C - Chambre 3',
                    isAvailable: true,
                    description: 'Chambre 3 du Bloc C',
                },
                {
                    type: 'M',
                    capacity: 4,
                    occupancyStatus: Status.DISPONIBLE,
                    availableSpots: 4,
                    location: 'Home C - Chambre 4',
                    isAvailable: true,
                    description: 'Chambre 4 du Bloc C',
                },
                {
                    type: 'M',
                    capacity: 4,
                    occupancyStatus: Status.DISPONIBLE,
                    availableSpots: 4,
                    location: 'Home C - Chambre 5',
                    isAvailable: true,
                    description: 'Chambre 5 du Bloc C',
                },

                {
                    type: 'M',
                    capacity: 4,
                    occupancyStatus: Status.DISPONIBLE,
                    availableSpots: 4,
                    location: 'Home D - Chambre 1',
                    isAvailable: true,
                    description: 'Chambre 1 du Bloc D',
                },
                {
                    type: 'M',
                    capacity: 4,
                    occupancyStatus: Status.DISPONIBLE,
                    availableSpots: 4,
                    location: 'Home D - Chambre 2',
                    isAvailable: true,
                    description: 'Chambre 2 du Bloc D',
                },
                {
                    type: 'M',
                    capacity: 4,
                    occupancyStatus: Status.DISPONIBLE,
                    availableSpots: 4,
                    location: 'Home D - Chambre 3',
                    isAvailable: true,
                    description: 'Chambre 3 du Bloc D',
                },
                {
                    type: 'M',
                    capacity: 4,
                    occupancyStatus: Status.DISPONIBLE,
                    availableSpots: 4,
                    location: 'Home D - Chambre 4',
                    isAvailable: true,
                    description: 'Chambre 4 du Bloc D',
                },
                {
                    type: 'M',
                    capacity: 4,
                    occupancyStatus: Status.DISPONIBLE,
                    availableSpots: 4,
                    location: 'Home D - Chambre 5',
                    isAvailable: true,
                    description: 'Chambre 5 du Bloc D',
                },

                {
                    type: 'M',
                    capacity: 4,
                    occupancyStatus: Status.DISPONIBLE,
                    availableSpots: 4,
                    location: 'Home E - Chambre 1',
                    isAvailable: true,
                    description: 'Chambre 1 du Bloc E',
                },
                {
                    type: 'M',
                    capacity: 4,
                    occupancyStatus: Status.DISPONIBLE,
                    availableSpots: 4,
                    location: 'Home E - Chambre 2',
                    isAvailable: true,
                    description: 'Chambre 2 du Bloc E',
                },
                {
                    type: 'M',
                    capacity: 4,
                    occupancyStatus: Status.DISPONIBLE,
                    availableSpots: 4,
                    location: 'Home E - Chambre 3',
                    isAvailable: true,
                    description: 'Chambre 3 du Bloc E',
                },
                {
                    type: 'M',
                    capacity: 4,
                    occupancyStatus: Status.DISPONIBLE,
                    availableSpots: 4,
                    location: 'Home E - Chambre 4',
                    isAvailable: true,
                    description: 'Chambre 4 du Bloc E',
                },
                {
                    type: 'M',
                    capacity: 4,
                    occupancyStatus: Status.DISPONIBLE,
                    availableSpots: 4,
                    location: 'Home E - Chambre 5',
                    isAvailable: true,
                    description: 'Chambre 5 du Bloc E',
                },
            ])
        }
    }
}
